### ISSUE TITLE
generate exception with -c argument

### ISSUE THREAD

**Issue by LemADEC** [trentech/ProjectBorders#4]
As of projectborders-5.0.0-0.1.4.jar, generate -c argument fails to cast to Integer:
```
[18:49:59] [Server thread/INFO] [nucleus]: Server ran the command: /border generate Teal -verbose -c 10.0
[18:49:59] [Server thread/INFO]: Error occurred while executing command: java.lang.Double cannot be cast to java.lang.Integer
[18:49:59] [Server thread/ERROR] [Sponge]: Error occurred while executing command 'border generate Teal -verbose -c 10.0' for source DedicatedServer: java.lang.Double cannot be cast to java.lang.Integer
java.lang.ClassCastException: java.lang.Double cannot be cast to java.lang.Integer
>       at com.gmail.trentech.pjb.commands.CMDGenerate.execute(CMDGenerate.java:70) ~[CMDGenerate.class:?]
>       at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:179) ~[ChildCommandElementExecutor.class:1.10.2-2202-5.1.0-BETA-2020]
>       at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:351) ~[CommandSpec.class:1.10.2-2202-5.1.0-BETA-2020]
>       at org.spongepowered.api.command.dispatcher.SimpleDispatcher.process(SimpleDispatcher.java:333) ~[SimpleDispatcher.class:1.10.2-2202-5.1.0-BETA-2020]
>       at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:294) [SpongeCommandManager.class:1.10.2-2202-5.1.0-BETA-2020]
>       at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:83) [bd.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71333_ah(DedicatedServer.java:423) [ld.class:?]
>       at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:388) [ld.class:?]
>       at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613) [MinecraftServer.class:?]
>       at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471) [MinecraftServer.class:?]
>       at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
```

**Comment by trentech** [comment]
10.0 is a double. You need to enter a integer. Simply 10 without a decimal

**Comment by trentech** [comment]
Oh wait, I see what happened
